language: cpp
os: linux
dist: bionic

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - sudo apt-get install python3
  - sudo pip3 install conan

script:
  - conan install .
  - cmake --build .
