language: cpp
os: linux
dist: bionic

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install xorg-dev
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - pip3 install wheel
  - pip3 install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.version=9 default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - conan install . --build missing
  - cmake --build .
